// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BaseData: typeof import('./src/components/table/BaseData.vue')['default']
    BaseTable: typeof import('./src/components/table/BaseTable.vue')['default']
    MatchData: typeof import('./src/components/MatchData.vue')['default']
    MatchRow: typeof import('./src/components/MatchRow.vue')['default']
    PoolTable: typeof import('./src/components/PoolTable.vue')['default']
    ScheduleTable: typeof import('./src/components/ScheduleTable.vue')['default']
  }
}

export { }
