// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    BaseDropDown: typeof import('./src/components/base/BaseDropDown.vue')['default']
    BaseModal: typeof import('./src/components/base/BaseModal.vue')['default']
    BaseTable: typeof import('./src/components/base/BaseTable.vue')['default']
    BaseToggle: typeof import('./src/components/base/BaseToggle.vue')['default']
    I18NProvider: typeof import('./src/providers/I18NProvider.vue')['default']
    IHcsIconsCamo: typeof import('~icons/hcs-icons/camo')['default']
    IHcsIconsHaloCalendar: typeof import('~icons/hcs-icons/halo-calendar')['default']
    IMdiCursorDefault: typeof import('~icons/mdi/cursor-default')['default']
    IMdiCursorDefaultClick: typeof import('~icons/mdi/cursor-default-click')['default']
    IMdiInformationOutline: typeof import('~icons/mdi/information-outline')['default']
    IMdiRadar: typeof import('~icons/mdi/radar')['default']
    IMdiThemeLightDark: typeof import('~icons/mdi/theme-light-dark')['default']
    IMdiTranslate: typeof import('~icons/mdi/translate')['default']
    MatchData: typeof import('./src/components/match/MatchData.vue')['default']
    PoolTable: typeof import('./src/components/table/PoolTable.vue')['default']
    PoolTableItem: typeof import('./src/components/table/PoolTableItem.vue')['default']
    ReloadPrompt: typeof import('./src/components/ReloadPrompt.vue')['default']
    ScheduleTable: typeof import('./src/components/table/ScheduleTable.vue')['default']
    TableData: typeof import('./src/components/base/TableData.vue')['default']
  }
}

export { }
